spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:h2:~/test
    url: jdbc:log4jdbc:h2:~/test
    username: sa
    password: sa
    driver-class-name: net.sf.log4jdbc.DriverSpy
#    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
#        trace: true
      path: /h2
logging:
  level:
    jdbc: error
    jdbc.sqltiming: info
